// Benson pulse — TikTok progress briefs (generated by the benson-pulse worker)
// and manual trigger endpoints for testing/ops.

import { Hono } from 'hono';
import { getLatestProgressBrief, runTikTokPulse } from '@social-agent/core/benson-pulse';
import { runBensonLearningCycle } from '@social-agent/core/benson-learning';
import { classifyError, sanitizeErrorForUi } from '@social-agent/core/provider-errors';
import { scoreUnscoredItems, getTopScoredOpportunities } from '@social-agent/core/opportunity-scoring';
import { runSourceHealthCheck, listSourceProposals } from '@social-agent/core/source-health';

export const bensonPulseRoute = new Hono();

bensonPulseRoute.get('/latest', async (c) => {
  const brief = await getLatestProgressBrief();
  return c.json({ ok: true, brief });
});

bensonPulseRoute.post('/run', async (c) => {
  const skipSync = c.req.query('skip_sync') === 'true';
  try {
    const [result, learning] = await Promise.all([
      runTikTokPulse({ skipSync }),
      runBensonLearningCycle().catch((err) => {
        const classified = classifyError(err, 'openai');
        console.error(
          `[benson-pulse/run] learning refresh failed (${classified.rootCause}${classified.requestId ? `, ${classified.requestId}` : ''}): ${classified.logMessage}`,
        );
        return {
          ran: false,
          reason: 'learning_refresh_failed',
          refreshFailed: true,
        };
      }),
    ]);
    return c.json({ ok: result.ok, result, learning });
  } catch (err) {
    const classified = classifyError(err, 'openai');
    console.error(
      `[benson-pulse/run] pulse failed (${classified.rootCause}${classified.requestId ? `, ${classified.requestId}` : ''}): ${classified.logMessage}`,
    );
    return c.json({ ok: false, error: sanitizeErrorForUi(err, 'pulse') }, 500);
  }
});

bensonPulseRoute.post('/score-opportunities', async (c) => {
  const limit = parseInt(c.req.query('limit') ?? '36', 10);
  try {
    const result = await scoreUnscoredItems({ limit });
    return c.json({ ok: true, result });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return c.json({ ok: false, error: message }, 500);
  }
});

bensonPulseRoute.get('/top-opportunities', async (c) => {
  const limit = parseInt(c.req.query('limit') ?? '5', 10);
  const opportunities = await getTopScoredOpportunities({ limit });
  return c.json({ ok: true, opportunities });
});

bensonPulseRoute.post('/source-health', async (c) => {
  const propose = c.req.query('propose') !== 'false';
  try {
    const result = await runSourceHealthCheck({ proposeReplacements: propose });
    return c.json({ ok: true, result });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return c.json({ ok: false, error: message }, 500);
  }
});

bensonPulseRoute.get('/source-proposals', async (c) => {
  const status = c.req.query('status') ?? undefined;
  const proposals = await listSourceProposals(status);
  return c.json({ ok: true, proposals });
});
