/**
 * Researched Kansas City metro early-signal sources.
 * Each entry was URL-checked before inclusion. Run `pnpm probe:early-signal-sources` to re-verify.
 */

export type SourceCatalogEntry = {
  sourceName: string;
  sourceUrl: string;
  sourceCategory: string;
  adapterType: 'html_watch' | 'rss_feed' | 'socrata_json';
  checkFrequencyMs: number;
  jurisdiction: string;
  format: string;
  signalsRevealed: string;
  expectedLeadTime: string;
  reliabilityScore: number;
  /** active = seeded and enabled; rejected = researched but not usable */
  catalogStatus: 'active' | 'rejected';
  rejectionReason?: string;
  config?: Record<string, unknown>;
};

/** URLs that were seeded previously but failed verification — disabled on seed. */
export const REJECTED_SOURCE_URLS: Array<{ url: string; reason: string }> = [
  {
    url: 'https://crossroadskc.org/events/',
    reason: 'HTTP 404 — domain now serves Crossroads Charter Schools, not the arts district',
  },
  {
    url: 'https://crossroadskc.org/',
    reason: 'Wrong organization (Crossroads Charter Schools)',
  },
];

export const KC_SOURCE_CATALOG: SourceCatalogEntry[] = [
  // --- KCMO open data ---
  {
    sourceName: 'KCMO Commercial Permits (tenant finish / remodel)',
    sourceUrl: 'https://data.kcmo.org/resource/ntw8-aacc.json',
    sourceCategory: 'city_permit',
    adapterType: 'socrata_json',
    checkFrequencyMs: 12 * 60 * 60 * 1000,
    jurisdiction: 'Kansas City, MO',
    format: 'Socrata JSON API',
    signalsRevealed: 'Tenant finish, commercial remodel, change of use, certificate of occupancy',
    expectedLeadTime: '2–12 weeks before opening',
    reliabilityScore: 0.88,
    catalogStatus: 'active',
    config: {
      socrataQuery:
        "$where=issueddate > '2025-01-01' AND permitclassmapped='NON-RESIDENTIAL' AND (upper(description) like '%TENANT%' OR upper(permittype) like '%TENANT%' OR upper(description) like '%COMMERCIAL REMODEL%' OR upper(permittype) like '%CHANGE OF USE%' OR upper(permittype) like '%CERTIFICATE OF OCCUPANCY%')&$order=issueddate DESC&$limit=20",
      textFields: ['projectname', 'description', 'permittype', 'permittypedesc', 'workclass'],
      addressFields: ['originaladdress1'],
      cityField: 'originalcity',
      stateField: 'originalstate',
      entityField: 'projectname',
      linkField: 'link',
      idField: 'permitnum',
      dateField: 'issueddate',
      matchPatterns: [
        'tenant',
        'commercial remodel',
        'change of use',
        'certificate of occupancy',
        'tenant finish',
      ],
      signalType: 'permit',
      city: 'Kansas City',
      state: 'MO',
    },
  },
  {
    sourceName: 'KCMO Business Licenses (liquor / beer / wine)',
    sourceUrl: 'https://data.kcmo.org/resource/pnm4-68wg.json',
    sourceCategory: 'business_license',
    adapterType: 'socrata_json',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Kansas City, MO',
    format: 'Socrata JSON API',
    signalsRevealed: 'New or updated liquor, beer, and wine retail licenses',
    expectedLeadTime: '2–8 weeks before opening',
    reliabilityScore: 0.82,
    catalogStatus: 'active',
    config: {
      socrataQuery:
        "$where=upper(business_type) like '%LIQUOR%' OR upper(business_type) like '%BEER%' OR upper(business_type) like '%WINE%'&$order=id DESC&$limit=25",
      textFields: ['dba_name', 'business_name', 'business_type', 'address'],
      addressFields: ['address'],
      cityField: 'city',
      stateField: 'state',
      entityField: 'dba_name',
      idField: 'id',
      matchPatterns: ['liquor', 'beer', 'wine'],
      signalType: 'permit',
      city: 'Kansas City',
      state: 'MO',
    },
  },
  {
    sourceName: 'Missouri New Liquor Licenses (KC metro cities)',
    sourceUrl: 'https://data.mo.gov/resource/dymb-xy5c.json',
    sourceCategory: 'liquor_license',
    adapterType: 'socrata_json',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Missouri — KC metro',
    format: 'Socrata JSON API (ATC)',
    signalsRevealed: 'New retail-by-drink and package liquor licenses in metro cities',
    expectedLeadTime: '2–6 weeks before opening',
    reliabilityScore: 0.9,
    catalogStatus: 'active',
    config: {
      socrataQuery:
        "$where=upper(city) in ('KANSAS CITY','INDEPENDENCE','LEE''S SUMMIT','OVERLAND PARK','OLATHE','SHAWNEE','LENEXA','BLUE SPRINGS','LIBERTY','GLADSTONE','RAYTOWN','GRANDVIEW','LEAWOOD','PRAIRIE VILLAGE','NORTH KANSAS CITY','KANSAS CITY, KANSAS')&$order=original_date DESC&$limit=30",
      textFields: ['licensee', 'dbaname', 'license_type', 'businesstype', 'street', 'city'],
      addressFields: ['street_number', 'street'],
      cityField: 'city',
      stateField: 'state',
      entityField: 'dbaname',
      idField: 'license_number',
      dateField: 'original_date',
      matchPatterns: ['retail', 'liquor', 'drink', 'package', 'wine', 'beer'],
      signalType: 'permit',
    },
  },
  // --- Planning / liquor agendas (HTML) ---
  {
    sourceName: 'KCMO Legistar Calendar (planning + liquor board)',
    sourceUrl: 'https://kansascity.legistar.com/Calendar.aspx',
    sourceCategory: 'planning_agenda',
    adapterType: 'html_watch',
    checkFrequencyMs: 12 * 60 * 60 * 1000,
    jurisdiction: 'Kansas City, MO',
    format: 'HTML calendar (Granicus Legistar)',
    signalsRevealed: 'Planning hearings, special use permits, liquor control board reviews, plats',
    expectedLeadTime: '2–8 weeks',
    reliabilityScore: 0.86,
    catalogStatus: 'active',
    config: { city: 'Kansas City', state: 'MO' },
  },
  {
    sourceName: "Lee's Summit Legistar Calendar",
    sourceUrl: 'https://lsmo.legistar.com/Calendar.aspx',
    sourceCategory: 'planning_agenda',
    adapterType: 'html_watch',
    checkFrequencyMs: 12 * 60 * 60 * 1000,
    jurisdiction: "Lee's Summit, MO",
    format: 'HTML calendar (Granicus Legistar)',
    signalsRevealed: 'Planning commission hearings, special use permits, plats, rezonings',
    expectedLeadTime: '2–10 weeks',
    reliabilityScore: 0.86,
    catalogStatus: 'active',
    config: { city: "Lee's Summit", state: 'MO' },
  },
  {
    sourceName: 'Overland Park Planning Commission',
    sourceUrl: 'https://www.opkansas.org/city-government/boards-commissions/planning-commission/',
    sourceCategory: 'planning_agenda',
    adapterType: 'html_watch',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Overland Park, KS',
    format: 'HTML',
    signalsRevealed: 'Final plats, special use permits, rezonings, development plans',
    expectedLeadTime: '1–3 months',
    reliabilityScore: 0.84,
    catalogStatus: 'active',
    config: { city: 'Overland Park', state: 'KS' },
  },
  {
    sourceName: 'Johnson County Planning Commission',
    sourceUrl: 'https://www.jocogov.org/department/planning/johnson-county-planning-commission',
    sourceCategory: 'planning_agenda',
    adapterType: 'html_watch',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Johnson County, KS',
    format: 'HTML',
    signalsRevealed: 'County planning hearings, zoning amendments, subdivisions',
    expectedLeadTime: '1–3 months',
    reliabilityScore: 0.83,
    catalogStatus: 'active',
    config: { city: 'Olathe', state: 'KS' },
  },
  {
    sourceName: 'Independence MO Planning Commission',
    sourceUrl:
      'https://www.independencemo.gov/government/city-departments/city-clerk/boards-and-commissions/planning-commission',
    sourceCategory: 'planning_agenda',
    adapterType: 'html_watch',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Independence, MO',
    format: 'HTML agendas',
    signalsRevealed: 'Rezonings, plats, special uses, UDO amendments',
    expectedLeadTime: '2–10 weeks',
    reliabilityScore: 0.83,
    catalogStatus: 'active',
    config: { city: 'Independence', state: 'MO' },
  },
  {
    sourceName: "Lee's Summit Development Project List",
    sourceUrl:
      'https://cityofls.net/development-services/planning-development/development-project-list',
    sourceCategory: 'planning_agenda',
    adapterType: 'html_watch',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: "Lee's Summit, MO",
    format: 'HTML project tracker',
    signalsRevealed: 'Active commercial and residential development applications',
    expectedLeadTime: '1–4 months',
    reliabilityScore: 0.8,
    catalogStatus: 'active',
    config: { city: "Lee's Summit", state: 'MO' },
  },
  // --- Chambers / retail / venues ---
  {
    sourceName: 'KC Chamber Events (ribbon cuttings)',
    sourceUrl: 'https://www.kcchamber.com/events',
    sourceCategory: 'chamber',
    adapterType: 'html_watch',
    checkFrequencyMs: 12 * 60 * 60 * 1000,
    jurisdiction: 'Greater Kansas City',
    format: 'HTML events calendar',
    signalsRevealed: 'Ribbon cuttings, grand openings, chamber member milestones',
    expectedLeadTime: '1–4 weeks',
    reliabilityScore: 0.78,
    catalogStatus: 'active',
    config: { city: 'Kansas City', state: 'MO' },
  },
  {
    sourceName: 'Oak Park Mall Directory (Coming Soon)',
    sourceUrl: 'https://www.theoakparkmall.com/directory',
    sourceCategory: 'shopping_center',
    adapterType: 'html_watch',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Overland Park, KS',
    format: 'HTML tenant directory',
    signalsRevealed: 'New mall tenants, coming-soon retailers',
    expectedLeadTime: '2–8 weeks',
    reliabilityScore: 0.72,
    catalogStatus: 'active',
    config: { city: 'Overland Park', state: 'KS' },
  },
  {
    sourceName: 'Visit KC Events RSS',
    sourceUrl: 'https://www.visitkc.com/events/feed/',
    sourceCategory: 'venue_calendar',
    adapterType: 'rss_feed',
    checkFrequencyMs: 6 * 60 * 60 * 1000,
    jurisdiction: 'Kansas City metro',
    format: 'RSS',
    signalsRevealed: 'Major events, festivals, ticket on-sale dates',
    expectedLeadTime: '1–8 weeks',
    reliabilityScore: 0.75,
    catalogStatus: 'active',
  },
  {
    sourceName: 'Union Station KC Events',
    sourceUrl: 'https://unionstation.org/events/',
    sourceCategory: 'venue_calendar',
    adapterType: 'html_watch',
    checkFrequencyMs: 12 * 60 * 60 * 1000,
    jurisdiction: 'Kansas City, MO',
    format: 'HTML',
    signalsRevealed: 'Exhibitions, ticketed events, venue announcements',
    expectedLeadTime: '2–8 weeks',
    reliabilityScore: 0.76,
    catalogStatus: 'active',
    config: { city: 'Kansas City', state: 'MO' },
  },
  {
    sourceName: 'Crossroads Arts District Events',
    sourceUrl: 'https://kccrossroads.org/events/',
    sourceCategory: 'business_district',
    adapterType: 'html_watch',
    checkFrequencyMs: 12 * 60 * 60 * 1000,
    jurisdiction: 'Crossroads, Kansas City MO',
    format: 'HTML',
    signalsRevealed: 'Gallery openings, First Friday, district festivals, new venue programming',
    expectedLeadTime: '1–4 weeks',
    reliabilityScore: 0.74,
    catalogStatus: 'active',
    config: { city: 'Kansas City', state: 'MO' },
  },
  // --- Rejected (documented alternatives) ---
  {
    sourceName: 'Wyandotte County Accela Permits (KCK)',
    sourceUrl: 'https://aca-prod.accela.com/UG/Cap/CapHome.aspx?module=Building',
    sourceCategory: 'city_permit',
    adapterType: 'html_watch',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Kansas City, KS / Wyandotte',
    format: 'Interactive Accela portal',
    signalsRevealed: 'Building permits (search-only)',
    expectedLeadTime: 'N/A',
    reliabilityScore: 0,
    catalogStatus: 'rejected',
    rejectionReason:
      'Interactive search portal only — no public bulk feed. Use manual tips or email ingestion for KCK permit leads.',
  },
  {
    sourceName: 'Independence Permit Portal',
    sourceUrl: 'https://apps.indepmo.org/comdev/SearchPermitStatus',
    sourceCategory: 'city_permit',
    adapterType: 'html_watch',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Independence, MO',
    format: 'Interactive portal',
    signalsRevealed: 'Permit status lookup',
    expectedLeadTime: 'N/A',
    reliabilityScore: 0,
    catalogStatus: 'rejected',
    rejectionReason: 'Interactive lookup only — no list feed. Planning commission HTML adapter covers Independence.',
  },
  {
    sourceName: 'KC Chamber Membership Events Portal',
    sourceUrl: 'https://membership.kcchamber.com/events',
    sourceCategory: 'chamber',
    adapterType: 'html_watch',
    checkFrequencyMs: 12 * 60 * 60 * 1000,
    jurisdiction: 'Greater Kansas City',
    format: 'HTML (member portal)',
    signalsRevealed: 'Ribbon cuttings',
    expectedLeadTime: 'N/A',
    reliabilityScore: 0,
    catalogStatus: 'rejected',
    rejectionReason:
      'TLS/network failure from server environment — using www.kcchamber.com/events instead.',
  },
  {
    sourceName: 'Country Club Plaza Store Directory',
    sourceUrl: 'https://countryclubplaza.com/stores/',
    sourceCategory: 'shopping_center',
    adapterType: 'html_watch',
    checkFrequencyMs: 24 * 60 * 60 * 1000,
    jurisdiction: 'Kansas City, MO',
    format: 'JS-rendered SPA shell',
    signalsRevealed: 'Tenant changes',
    expectedLeadTime: 'N/A',
    reliabilityScore: 0,
    catalogStatus: 'rejected',
    rejectionReason:
      'Page returns minimal shell content without tenant list in server-side HTML — not parseable without browser automation.',
  },
  {
    sourceName: 'Crossroads KC (legacy URL)',
    sourceUrl: 'https://crossroadskc.org/events/',
    sourceCategory: 'business_district',
    adapterType: 'html_watch',
    checkFrequencyMs: 12 * 60 * 60 * 1000,
    jurisdiction: 'Crossroads',
    format: 'HTML',
    signalsRevealed: 'N/A',
    expectedLeadTime: 'N/A',
    reliabilityScore: 0,
    catalogStatus: 'rejected',
    rejectionReason: 'HTTP 404 — replaced by kccrossroads.org/events/',
  },
];

export const ACTIVE_KC_SOURCES = KC_SOURCE_CATALOG.filter((s) => s.catalogStatus === 'active');

/** @deprecated use ACTIVE_KC_SOURCES */
export const DEFAULT_KC_WATCHERS = ACTIVE_KC_SOURCES.map(
  ({ sourceName, sourceUrl, sourceCategory, adapterType, checkFrequencyMs, config }) => ({
    sourceName,
    sourceUrl,
    sourceCategory,
    adapterType,
    checkFrequencyMs,
    config,
  }),
);
