export {
  SPONSOR_PIPELINE_STATUSES,
  OPEN_PIPELINE_STATUSES,
  CLOSED_PIPELINE_STATUSES,
  PIPELINE_STATUS_LABELS,
  type SponsorPipelineStatus,
} from './constants.js';
export {
  listSponsorOpportunities,
  getSponsorOpportunity,
  enrichOpportunities,
  createSponsorOpportunity,
  updateSponsorOpportunity,
  markOpportunityWon,
  markOpportunityLost,
  getSponsorPipelineSummary,
  computePipelineDashboard,
  computePipelineReporting,
  createOpportunityFromIntelligence,
  ensurePipelineDealOnReply,
  listPipelineRelationships,
  getPipelineRelationshipForContact,
  RELATIONSHIP_STAGES,
  RELATIONSHIP_STAGE_LABEL,
  rowToOpportunity,
  type SponsorOpportunityRecord,
  type SponsorOpportunityWithContact,
  type SponsorPipelineSummary,
  type PipelineDashboard,
  type PipelineReporting,
  type PipelineRelationshipCard,
  type RelationshipStage,
} from './opportunities.js';
