/**
 * Canonical KC-metro venue registry for Calendar admission geographic evidence.
 * Venue-looking free text alone does not admit — only resolved registry hits do.
 */

export type CanonicalVenueRecord = {
  id: string;
  name: string;
  aliases: string[];
  address: string;
  city: string;
  state: 'MO' | 'KS';
  zip: string;
  lat: number;
  lng: number;
  /** True when the facility is inside the Benson KC service area. */
  serviceArea: boolean;
  evidence: string[];
  lastVerified: string;
};

/** Seeded from first-party Benson data + verified public venue pages. */
export const CANONICAL_KC_VENUES: CanonicalVenueRecord[] = [
  {
    id: 'kauffman-center',
    name: 'Kauffman Center for the Performing Arts',
    aliases: ['Kauffman Center', 'Kauffman Centre', 'Helzberg Hall', 'Muriel Kauffman Theatre'],
    address: '1601 Broadway Blvd',
    city: 'Kansas City',
    state: 'MO',
    zip: '64108',
    lat: 39.0975,
    lng: -94.5874,
    serviceArea: true,
    evidence: ['https://www.kauffmancenter.org/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'childrens-mercy-park',
    name: "Children's Mercy Park",
    aliases: ['Childrens Mercy Park', 'CMP', 'Sporting Park', 'Sporting KC Stadium'],
    address: '1 Sporting Way',
    city: 'Kansas City',
    state: 'KS',
    zip: '66111',
    lat: 39.1216,
    lng: -94.8235,
    serviceArea: true,
    evidence: ['https://www.sportingkc.com/stadium/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'waldo-branch-library',
    name: 'Waldo Branch Library',
    aliases: ['Waldo Branch', 'Kansas City Public Library Waldo', 'KCPL Waldo'],
    address: '201 E 75th St',
    city: 'Kansas City',
    state: 'MO',
    zip: '64114',
    lat: 38.9926,
    lng: -94.5891,
    serviceArea: true,
    evidence: ['https://kclibrary.org/locations/waldo'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'lakeside-nature-center',
    name: 'Lakeside Nature Center',
    aliases: ['Lakeside Nature Center KC', 'Swope Park Nature Center'],
    address: '4701 E Gregory Blvd',
    city: 'Kansas City',
    state: 'MO',
    zip: '64132',
    lat: 38.9972,
    lng: -94.5136,
    serviceArea: true,
    evidence: ['https://kcparks.org/places/lakeside-nature-center/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'op-convention-center',
    name: 'Overland Park Convention Center',
    aliases: ['OPCC', 'OP Convention Center', 'Overland Park Convention Centre'],
    address: '6000 College Blvd',
    city: 'Overland Park',
    state: 'KS',
    zip: '66211',
    lat: 38.9275,
    lng: -94.6711,
    serviceArea: true,
    evidence: ['https://opconventioncenter.com/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 't-mobile-center',
    name: 'T-Mobile Center',
    aliases: ['T Mobile Center', 'Sprint Center', 'TMobile Center'],
    address: '1407 Grand Blvd',
    city: 'Kansas City',
    state: 'MO',
    zip: '64106',
    lat: 39.0974,
    lng: -94.5801,
    serviceArea: true,
    evidence: ['https://www.t-mobilecenter.com/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'parkville-nature-sanctuary',
    name: 'Parkville Nature Sanctuary',
    aliases: ['The Parkville Nature Sanctuary', 'Parkville Nature Center'],
    address: '1201 E St',
    city: 'Parkville',
    state: 'MO',
    zip: '64152',
    lat: 39.1923,
    lng: -94.6821,
    serviceArea: true,
    evidence: ['https://parkvillemo.gov/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'woodys-westport',
    name: "Woody's",
    aliases: ["Woody's Bar", "Woody's Westport", 'Woodys'],
    address: '4800 Main St',
    city: 'Kansas City',
    state: 'MO',
    zip: '64112',
    lat: 39.0421,
    lng: -94.5902,
    serviceArea: true,
    evidence: ['https://www.thepitchkc.com/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'level-kc',
    name: 'Level KC',
    aliases: ['Level Kansas City', 'Level Nightclub KC'],
    address: '1020 Westport Rd',
    city: 'Kansas City',
    state: 'MO',
    zip: '64111',
    lat: 39.0526,
    lng: -94.5965,
    serviceArea: true,
    evidence: ['first_party_watchlist'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'kansas-city-pickle-club',
    name: 'Kansas City Pickle Club',
    aliases: ['KC Pickle Club', 'Kansas City Pickleball Club'],
    address: '2001 Main St',
    city: 'Kansas City',
    state: 'MO',
    zip: '64108',
    lat: 39.0891,
    lng: -94.5835,
    serviceArea: true,
    evidence: ['first_party_watchlist'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'union-station',
    name: 'Union Station',
    aliases: ['Union Station Kansas City', 'Science City at Union Station'],
    address: '30 W Pershing Rd',
    city: 'Kansas City',
    state: 'MO',
    zip: '64108',
    lat: 39.0847,
    lng: -94.5855,
    serviceArea: true,
    evidence: ['https://unionstation.org/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'juke-house',
    name: 'Juke House',
    aliases: ['Juke House KC', 'The Juke House'],
    address: '1715 Westport Rd',
    city: 'Kansas City',
    state: 'MO',
    zip: '64111',
    lat: 39.0528,
    lng: -94.5991,
    serviceArea: true,
    evidence: ['first_party_watchlist'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'starlight-theatre',
    name: 'Starlight Theatre',
    aliases: ['Starlight Theater', 'KC Starlight'],
    address: '4600 Starlight Rd',
    city: 'Kansas City',
    state: 'MO',
    zip: '64132',
    lat: 39.0065,
    lng: -94.5321,
    serviceArea: true,
    evidence: ['https://kcstarlight.com/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'midland-theatre',
    name: 'Midland Theatre',
    aliases: ['The Midland', 'Midland KC'],
    address: '1228 Main St',
    city: 'Kansas City',
    state: 'MO',
    zip: '64105',
    lat: 39.0989,
    lng: -94.5836,
    serviceArea: true,
    evidence: ['https://www.midlandkc.com/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'kc-parks-board-room',
    name: 'Board of Parks and Recreation Commissioners Meeting Room',
    aliases: [
      'KC Parks Board Meeting',
      'Parks Board Meeting Room',
      'Board of Parks and Recreation Commissioners',
    ],
    address: '4600 E 63rd St',
    city: 'Kansas City',
    state: 'MO',
    zip: '64130',
    lat: 39.0142,
    lng: -94.5261,
    serviceArea: true,
    evidence: ['https://kcparks.org/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'central-library-kcpl',
    name: 'Central Library',
    aliases: ['KCPL Central', 'Kansas City Public Library Central'],
    address: '14 W 10th St',
    city: 'Kansas City',
    state: 'MO',
    zip: '64105',
    lat: 39.1012,
    lng: -94.5839,
    serviceArea: true,
    evidence: ['https://kclibrary.org/locations/central'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'plaza-branch-library',
    name: 'Plaza Branch Library',
    aliases: ['KCPL Plaza', 'Plaza Library'],
    address: '4801 Main St',
    city: 'Kansas City',
    state: 'MO',
    zip: '64112',
    lat: 39.0425,
    lng: -94.5905,
    serviceArea: true,
    evidence: ['https://kclibrary.org/locations/plaza'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'joco-central-resource',
    name: 'Central Resource Library',
    aliases: [
      'Johnson County Central Resource Library',
      'JOCO Central Resource',
      'Central Resource Library JOCL',
    ],
    address: '9875 W 87th St',
    city: 'Overland Park',
    state: 'KS',
    zip: '66212',
    lat: 38.9731,
    lng: -94.6952,
    serviceArea: true,
    evidence: ['https://www.jocolibrary.org/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'loose-park',
    name: 'Loose Park',
    aliases: ['Laura Conyers Smith Municipal Rose Garden', 'Rose Garden Loose Park'],
    address: '5200 Pennsylvania Ave',
    city: 'Kansas City',
    state: 'MO',
    zip: '64112',
    lat: 39.0331,
    lng: -94.5945,
    serviceArea: true,
    evidence: ['https://kcparks.org/places/loose-park/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'arrowhead-stadium',
    name: 'GEHA Field at Arrowhead Stadium',
    aliases: ['Arrowhead', 'Arrowhead Stadium'],
    address: '1 Arrowhead Dr',
    city: 'Kansas City',
    state: 'MO',
    zip: '64129',
    lat: 39.0489,
    lng: -94.4839,
    serviceArea: true,
    evidence: ['https://www.chiefs.com/stadium/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'kauffman-stadium',
    name: 'Kauffman Stadium',
    aliases: ['The K', 'Kaufman Stadium'],
    address: '1 Royal Way',
    city: 'Kansas City',
    state: 'MO',
    zip: '64129',
    lat: 39.0517,
    lng: -94.4803,
    serviceArea: true,
    evidence: ['https://www.mlb.com/royals/ballpark'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'americas-community-center',
    name: "America's Community Center",
    aliases: ['Americas Community Center', 'ACC OP'],
    address: '9701 Renner Blvd',
    city: 'Lenexa',
    state: 'KS',
    zip: '66219',
    lat: 38.9572,
    lng: -94.7751,
    serviceArea: true,
    evidence: ['https://www.lenexa.com/'],
    lastVerified: '2026-09-13',
  },
  {
    id: 'rock-island-bridge',
    name: 'Rock Island Bridge',
    aliases: ['The Rock Island Bridge'],
    address: '100 Rock Island Bridge',
    city: 'Kansas City',
    state: 'KS',
    zip: '66118',
    lat: 39.1135,
    lng: -94.6251,
    serviceArea: true,
    evidence: ['first_party_watchlist'],
    lastVerified: '2026-09-13',
  },
];
