import type { SaveProgramLibraryInput } from './types.js';

/** Operator-supplied master list — do not auto-verify during seed. */
export const PROGRAM_LIBRARY_SEED_RECORDS: SaveProgramLibraryInput[] = [
  {
    brandName: 'FlexPro Meals',
    programName: 'FlexPro Meals',
    programType: 'affiliate',
    scope: 'kc_local',
    commissionBenefit: '5%',
    audienceBenefit: '40%',
    locationNote: 'Troost',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'KC Wine Road',
    programName: 'KC Wine Road',
    programType: 'affiliate',
    scope: 'kc_local',
    commissionBenefit: '10%',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'KC Chiefs Pro Shop',
    programName: 'KC Chiefs Pro Shop',
    programType: 'affiliate',
    scope: 'kc_local',
    commissionBenefit: '8%',
    affiliateNetwork: 'Impact',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'Dream KC Smoke Shop',
    programName: 'Dream KC Smoke Shop',
    programType: 'affiliate',
    scope: 'kc_local',
    commissionBenefit: '10%',
    cookieWindow: '90 days',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'BodymetRx KC',
    programName: 'BodymetRx KC',
    programType: 'affiliate',
    scope: 'kc_local',
    locationNote: 'Overland Park',
    commissionBenefit: 'unpublished / unknown',
    notes: 'affiliate/referral',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'KC Cabinetry & Stone',
    programName: 'KC Cabinetry & Stone',
    programType: 'referral',
    scope: 'kc_local',
    commissionBenefit: 'referral bonus (amount unspecified)',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'Prestige Transportation KC',
    programName: 'Prestige Transportation KC',
    programType: 'affiliate',
    scope: 'kc_local',
    commissionBenefit: 'unspecified',
    notes: 'affiliate/referral',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'LEGOLAND Discovery Center Kansas City',
    programName: 'LEGOLAND Discovery Center Kansas City',
    programType: 'affiliate',
    scope: 'kc_local',
    commissionBenefit: '2%',
    affiliateNetwork: 'Partnerize',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'LM Connect KC',
    programName: 'LM Connect KC',
    programType: 'influencer',
    scope: 'kc_local',
    notes: 'influencer hub; terms unspecified',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'Missouri Restaurant Association',
    programName: 'Missouri Restaurant Association',
    programType: 'influencer',
    scope: 'regional',
    notes: 'influencer program; terms unspecified',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'FASHIONPHILE',
    programName: 'FASHIONPHILE',
    programType: 'affiliate',
    scope: 'national',
    commissionBenefit: '5% + $50',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'The RealReal',
    programName: 'The RealReal',
    programType: 'affiliate',
    scope: 'national',
    commissionBenefit: '5%',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'thredUP',
    programName: 'thredUP',
    programType: 'affiliate',
    scope: 'national',
    commissionBenefit: '5–15%',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'Poshmark',
    programName: 'Poshmark',
    programType: 'affiliate',
    scope: 'national',
    commissionBenefit: '1–5%',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
  {
    brandName: 'LTK',
    programName: 'LTK',
    programType: 'creator',
    scope: 'national',
    commissionBenefit: '10–25% average',
    notes: 'creator/affiliate',
    operatorSupplied: true,
    operatorSuppliedMasterList: true,
    sourceScreen: 'program_library_seed',
  },
];
