import { countVideosForPlatform, importVideoRows } from './import.js';
import type { ImportVideoRow } from './types.js';

function daysAgo(n: number, hour = 18): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

const DEMO_VIDEOS: ImportVideoRow[] = [
  {
    video_id: 'demo_tt_001',
    title: 'Hidden gem coffee in Crossroads',
    caption: 'POV: you find the best latte in KC ☕ #kansascity #crossroads',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_001',
    published_at: daysAgo(3, 18),
    content_category: 'dining',
    content_pillar: 'local_secret',
    location_tag: 'Crossroads',
    sponsor_tag: 'local_coffee',
    views: 48200,
    likes: 4200,
    comments: 312,
    shares: 890,
    saves: 2100,
    watch_time_seconds: 384000,
    average_watch_duration_seconds: 8.2,
    completion_rate: 0.72,
    follower_count_snapshot: 125000,
  },
  {
    video_id: 'demo_tt_002',
    title: 'First Fridays gallery walk',
    caption: '3 stops you cannot miss this First Friday 🎨',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_002',
    published_at: daysAgo(7, 19),
    content_category: 'events',
    content_pillar: 'listicle',
    location_tag: 'Crossroads',
    sponsor_tag: null,
    views: 35600,
    likes: 3100,
    comments: 198,
    shares: 540,
    saves: 980,
    watch_time_seconds: 256000,
    average_watch_duration_seconds: 7.1,
    completion_rate: 0.65,
    follower_count_snapshot: 124200,
  },
  {
    video_id: 'demo_tt_003',
    title: 'Westport date night under $50',
    caption: 'Date night that feels expensive but is not 💕',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_003',
    published_at: daysAgo(10, 20),
    content_category: 'date_night',
    content_pillar: 'listicle',
    location_tag: 'Westport',
    sponsor_tag: 'restaurant',
    views: 62100,
    likes: 5800,
    comments: 420,
    shares: 1200,
    saves: 3400,
    watch_time_seconds: 520000,
    average_watch_duration_seconds: 9.4,
    completion_rate: 0.78,
    follower_count_snapshot: 123800,
  },
  {
    video_id: 'demo_tt_004',
    title: 'Estate sale treasure hunt',
    caption: 'Come with me to this Mission Hills estate sale 🏡',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_004',
    published_at: daysAgo(4, 9),
    content_category: 'estate_sale',
    content_pillar: 'storytime',
    location_tag: 'Mission Hills',
    sponsor_tag: null,
    views: 28900,
    likes: 2400,
    comments: 156,
    shares: 380,
    saves: 720,
    watch_time_seconds: 198000,
    average_watch_duration_seconds: 6.8,
    completion_rate: 0.61,
    follower_count_snapshot: 125100,
  },
  {
    video_id: 'demo_tt_005',
    title: 'New boutique opening on the Plaza',
    caption: 'Grand opening walkthrough ✨ #kcshopping',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_005',
    published_at: daysAgo(12, 17),
    content_category: 'retail',
    content_pillar: 'before_after',
    location_tag: 'Country Club Plaza',
    sponsor_tag: 'boutique_retail',
    views: 41500,
    likes: 3600,
    comments: 245,
    shares: 670,
    saves: 1500,
    watch_time_seconds: 310000,
    average_watch_duration_seconds: 7.5,
    completion_rate: 0.68,
    follower_count_snapshot: 123500,
  },
  {
    video_id: 'demo_tt_006',
    title: 'River Market weekend vendors',
    caption: 'Saturday morning at River Market 🍓',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_006',
    published_at: daysAgo(14, 10),
    content_category: 'markets',
    content_pillar: 'pov',
    location_tag: 'River Market',
    sponsor_tag: null,
    views: 19800,
    likes: 1600,
    comments: 98,
    shares: 210,
    saves: 430,
    watch_time_seconds: 142000,
    average_watch_duration_seconds: 6.2,
    completion_rate: 0.55,
    follower_count_snapshot: 123000,
  },
  {
    video_id: 'demo_tt_007',
    title: 'World Cup watch party spots',
    caption: 'Where to watch in KC ⚽🇺🇸',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_007',
    published_at: daysAgo(6, 19),
    content_category: 'world_cup',
    content_pillar: 'listicle',
    location_tag: 'Power & Light',
    sponsor_tag: 'sports_bar',
    views: 71200,
    likes: 6400,
    comments: 510,
    shares: 1800,
    saves: 2900,
    watch_time_seconds: 610000,
    average_watch_duration_seconds: 10.1,
    completion_rate: 0.81,
    follower_count_snapshot: 124900,
  },
  {
    video_id: 'demo_tt_008',
    title: 'Overland Park restaurant opening',
    caption: 'New spot alert 🍽️ soft opening this week',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_008',
    published_at: daysAgo(8, 18),
    content_category: 'restaurant_opening',
    content_pillar: 'urgency',
    location_tag: 'Overland Park',
    sponsor_tag: 'restaurant',
    views: 33400,
    likes: 2900,
    comments: 201,
    shares: 490,
    saves: 880,
    watch_time_seconds: 245000,
    average_watch_duration_seconds: 7.3,
    completion_rate: 0.64,
    follower_count_snapshot: 124500,
  },
  {
    video_id: 'demo_tt_009',
    title: 'Brookside hidden patio',
    caption: 'KC secret patio season is here',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_009',
    published_at: daysAgo(18, 19),
    content_category: 'dining',
    content_pillar: 'local_secret',
    location_tag: 'Brookside',
    sponsor_tag: 'restaurant',
    views: 45200,
    likes: 4100,
    comments: 280,
    shares: 760,
    saves: 1900,
    watch_time_seconds: 360000,
    average_watch_duration_seconds: 8.0,
    completion_rate: 0.71,
    follower_count_snapshot: 122800,
  },
  {
    video_id: 'demo_tt_010',
    title: 'Luxury hotel staycation',
    caption: 'Treat yourself KC staycation 🏨',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_010',
    published_at: daysAgo(21, 20),
    content_category: 'luxury',
    content_pillar: 'before_after',
    location_tag: 'Downtown KC',
    sponsor_tag: 'hotel',
    views: 38700,
    likes: 3300,
    comments: 190,
    shares: 520,
    saves: 1100,
    watch_time_seconds: 290000,
    average_watch_duration_seconds: 7.6,
    completion_rate: 0.66,
    follower_count_snapshot: 122400,
  },
  {
    video_id: 'demo_tt_011',
    title: 'Zona Rosa outlet haul',
    caption: 'Outlet finds under $30 🛍️',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_011',
    published_at: daysAgo(15, 14),
    content_category: 'retail',
    content_pillar: 'listicle',
    location_tag: 'Zona Rosa',
    sponsor_tag: 'outlet_retail',
    views: 27600,
    likes: 2200,
    comments: 140,
    shares: 350,
    saves: 620,
    watch_time_seconds: 210000,
    average_watch_duration_seconds: 6.9,
    completion_rate: 0.58,
    follower_count_snapshot: 123200,
  },
  {
    video_id: 'demo_tt_012',
    title: 'Union Station exhibit',
    caption: 'Free exhibit this month at Union Station',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_012',
    published_at: daysAgo(22, 11),
    content_category: 'events',
    content_pillar: 'storytime',
    location_tag: 'Union Station',
    sponsor_tag: null,
    views: 31200,
    likes: 2700,
    comments: 175,
    shares: 410,
    saves: 780,
    watch_time_seconds: 230000,
    average_watch_duration_seconds: 7.0,
    completion_rate: 0.62,
    follower_count_snapshot: 122100,
  },
  {
    video_id: 'demo_tt_013',
    title: 'Sporting KC matchday vibes',
    caption: 'Matchday at Childrens Mercy Park ⚽',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_013',
    published_at: daysAgo(9, 16),
    content_category: 'sports',
    content_pillar: 'pov',
    location_tag: 'Legends',
    sponsor_tag: 'sports',
    views: 54300,
    likes: 4800,
    comments: 390,
    shares: 980,
    saves: 1600,
    watch_time_seconds: 420000,
    average_watch_duration_seconds: 8.5,
    completion_rate: 0.74,
    follower_count_snapshot: 124300,
  },
  {
    video_id: 'demo_tt_014',
    title: 'Generic KC skyline timelapse',
    caption: 'KC hits different at golden hour',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_014',
    published_at: daysAgo(25, 7),
    content_category: 'general',
    content_pillar: 'pov',
    location_tag: 'Downtown KC',
    sponsor_tag: null,
    views: 8900,
    likes: 620,
    comments: 45,
    shares: 80,
    saves: 120,
    watch_time_seconds: 62000,
    average_watch_duration_seconds: 4.2,
    completion_rate: 0.35,
    follower_count_snapshot: 121900,
  },
  {
    video_id: 'demo_tt_015',
    title: 'Random parking lot clip',
    caption: 'testing new mic setup',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_015',
    published_at: daysAgo(28, 13),
    content_category: 'general',
    content_pillar: 'pov',
    location_tag: 'Midtown',
    sponsor_tag: null,
    views: 4200,
    likes: 210,
    comments: 18,
    shares: 12,
    saves: 45,
    watch_time_seconds: 28000,
    average_watch_duration_seconds: 3.1,
    completion_rate: 0.22,
    follower_count_snapshot: 121700,
  },
  {
    video_id: 'demo_tt_016',
    title: 'Westport date night rooftop',
    caption: 'Rooftop season in Westport 🌆',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_016',
    published_at: daysAgo(11, 20),
    content_category: 'date_night',
    content_pillar: 'local_secret',
    location_tag: 'Westport',
    sponsor_tag: 'restaurant',
    views: 58900,
    likes: 5200,
    comments: 380,
    shares: 1100,
    saves: 2600,
    watch_time_seconds: 480000,
    average_watch_duration_seconds: 9.1,
    completion_rate: 0.76,
    follower_count_snapshot: 124000,
  },
  {
    video_id: 'demo_tt_017',
    title: 'Crossroads mural tour',
    caption: '5 murals you need photos at',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_017',
    published_at: daysAgo(16, 18),
    content_category: 'events',
    content_pillar: 'listicle',
    location_tag: 'Crossroads',
    sponsor_tag: null,
    views: 40100,
    likes: 3500,
    comments: 230,
    shares: 620,
    saves: 1300,
    watch_time_seconds: 300000,
    average_watch_duration_seconds: 7.8,
    completion_rate: 0.69,
    follower_count_snapshot: 123100,
  },
  {
    video_id: 'demo_tt_018',
    title: 'Mission Hills estate sale part 2',
    caption: 'Part 2 — vintage finds 🕰️',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_018',
    published_at: daysAgo(5, 9),
    content_category: 'estate_sale',
    content_pillar: 'storytime',
    location_tag: 'Mission Hills',
    sponsor_tag: null,
    views: 31800,
    likes: 2600,
    comments: 170,
    shares: 420,
    saves: 810,
    watch_time_seconds: 220000,
    average_watch_duration_seconds: 7.0,
    completion_rate: 0.63,
    follower_count_snapshot: 125000,
  },
  {
    video_id: 'demo_tt_019',
    title: 'World Cup jersey shopping',
    caption: 'Where to grab kits in KC ⚽',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_019',
    published_at: daysAgo(13, 19),
    content_category: 'world_cup',
    content_pillar: 'listicle',
    location_tag: 'Country Club Plaza',
    sponsor_tag: 'retail',
    views: 49800,
    likes: 4300,
    comments: 310,
    shares: 850,
    saves: 1700,
    watch_time_seconds: 370000,
    average_watch_duration_seconds: 8.3,
    completion_rate: 0.73,
    follower_count_snapshot: 123600,
  },
  {
    video_id: 'demo_tt_020',
    title: 'Power & Light watch bar',
    caption: 'Best screens for the match ⚽',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_020',
    published_at: daysAgo(2, 19),
    content_category: 'world_cup',
    content_pillar: 'local_secret',
    location_tag: 'Power & Light',
    sponsor_tag: 'sports_bar',
    views: 68400,
    likes: 6100,
    comments: 480,
    shares: 1500,
    saves: 2700,
    watch_time_seconds: 580000,
    average_watch_duration_seconds: 9.8,
    completion_rate: 0.79,
    follower_count_snapshot: 125200,
  },
  {
    video_id: 'demo_tt_021',
    title: 'Brookside brunch spot',
    caption: 'Weekend brunch worth the wait',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_021',
    published_at: daysAgo(19, 11),
    content_category: 'dining',
    content_pillar: 'storytime',
    location_tag: 'Brookside',
    sponsor_tag: 'restaurant',
    views: 36700,
    likes: 3200,
    comments: 210,
    shares: 500,
    saves: 950,
    watch_time_seconds: 270000,
    average_watch_duration_seconds: 7.4,
    completion_rate: 0.67,
    follower_count_snapshot: 122600,
  },
  {
    video_id: 'demo_tt_022',
    title: 'Legends shopping weekend',
    caption: 'Legends outlets this weekend only',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_022',
    published_at: daysAgo(20, 15),
    content_category: 'retail',
    content_pillar: 'urgency',
    location_tag: 'Legends',
    sponsor_tag: 'outlet_retail',
    views: 25400,
    likes: 2000,
    comments: 120,
    shares: 290,
    saves: 510,
    watch_time_seconds: 190000,
    average_watch_duration_seconds: 6.5,
    completion_rate: 0.57,
    follower_count_snapshot: 122300,
  },
  {
    video_id: 'demo_tt_023',
    title: 'Charity gala preview',
    caption: 'Black tie season is back in KC',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_023',
    published_at: daysAgo(23, 20),
    content_category: 'charity',
    content_pillar: 'storytime',
    location_tag: 'Downtown KC',
    sponsor_tag: 'nonprofit',
    views: 22100,
    likes: 1800,
    comments: 110,
    shares: 260,
    saves: 480,
    watch_time_seconds: 165000,
    average_watch_duration_seconds: 6.4,
    completion_rate: 0.56,
    follower_count_snapshot: 122000,
  },
  {
    video_id: 'demo_tt_024',
    title: 'Crossroads coffee crawl',
    caption: '3 coffee shops in one afternoon ☕',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_024',
    published_at: daysAgo(17, 18),
    content_category: 'dining',
    content_pillar: 'listicle',
    location_tag: 'Crossroads',
    sponsor_tag: 'local_coffee',
    views: 51200,
    likes: 4600,
    comments: 340,
    shares: 920,
    saves: 2200,
    watch_time_seconds: 400000,
    average_watch_duration_seconds: 8.6,
    completion_rate: 0.75,
    follower_count_snapshot: 123300,
  },
  {
    video_id: 'demo_tt_025',
    title: 'Westport happy hour',
    caption: 'Happy hour deals you need',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_025',
    published_at: daysAgo(24, 17),
    content_category: 'date_night',
    content_pillar: 'listicle',
    location_tag: 'Westport',
    sponsor_tag: 'restaurant',
    views: 43800,
    likes: 3900,
    comments: 260,
    shares: 710,
    saves: 1400,
    watch_time_seconds: 330000,
    average_watch_duration_seconds: 7.9,
    completion_rate: 0.7,
    follower_count_snapshot: 121800,
  },
  {
    video_id: 'demo_tt_026',
    title: 'Another generic skyline',
    caption: 'skyline check',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_026',
    published_at: daysAgo(26, 8),
    content_category: 'general',
    content_pillar: 'pov',
    location_tag: 'Downtown KC',
    sponsor_tag: null,
    views: 7600,
    likes: 480,
    comments: 32,
    shares: 55,
    saves: 90,
    watch_time_seconds: 54000,
    average_watch_duration_seconds: 3.8,
    completion_rate: 0.28,
    follower_count_snapshot: 121600,
  },
  {
    video_id: 'demo_tt_027',
    title: 'River Market flower haul',
    caption: 'Saturday flowers at River Market 🌸',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_027',
    published_at: daysAgo(1, 10),
    content_category: 'markets',
    content_pillar: 'pov',
    location_tag: 'River Market',
    sponsor_tag: null,
    views: 29400,
    likes: 2500,
    comments: 165,
    shares: 400,
    saves: 760,
    watch_time_seconds: 205000,
    average_watch_duration_seconds: 6.9,
    completion_rate: 0.6,
    follower_count_snapshot: 125300,
  },
  {
    video_id: 'demo_tt_028',
    title: 'Plaza date night dessert',
    caption: 'Dessert crawl on the Plaza 🍰',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_028',
    published_at: daysAgo(27, 20),
    content_category: 'date_night',
    content_pillar: 'listicle',
    location_tag: 'Country Club Plaza',
    sponsor_tag: 'restaurant',
    views: 37900,
    likes: 3400,
    comments: 220,
    shares: 580,
    saves: 1050,
    watch_time_seconds: 285000,
    average_watch_duration_seconds: 7.5,
    completion_rate: 0.65,
    follower_count_snapshot: 121500,
  },
  {
    video_id: 'demo_tt_029',
    title: 'Overland Park opening day',
    caption: 'Grand opening lines were worth it',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_029',
    published_at: daysAgo(30, 18),
    content_category: 'restaurant_opening',
    content_pillar: 'urgency',
    location_tag: 'Overland Park',
    sponsor_tag: 'restaurant',
    views: 30100,
    likes: 2600,
    comments: 180,
    shares: 440,
    saves: 820,
    watch_time_seconds: 215000,
    average_watch_duration_seconds: 7.1,
    completion_rate: 0.62,
    follower_count_snapshot: 121200,
  },
  {
    video_id: 'demo_tt_030',
    title: 'Estate sale antique find',
    caption: 'Wait until you see what I found 🪑',
    post_url: 'https://www.tiktok.com/@kelliekc/video/demo_tt_030',
    published_at: daysAgo(29, 9),
    content_category: 'estate_sale',
    content_pillar: 'storytime',
    location_tag: 'Prairie Village',
    sponsor_tag: null,
    views: 26700,
    likes: 2300,
    comments: 150,
    shares: 360,
    saves: 690,
    watch_time_seconds: 188000,
    average_watch_duration_seconds: 6.7,
    completion_rate: 0.59,
    follower_count_snapshot: 121000,
  },
];

export async function seedDemoCreatorAnalytics(): Promise<{ imported: number; updated: number }> {
  const result = await importVideoRows(DEMO_VIDEOS, {
    platform: 'tiktok',
    username: 'kelliekc',
    source: 'demo',
  });
  return { imported: result.imported, updated: result.updated };
}

export async function ensureDemoCreatorAnalytics(): Promise<void> {
  const count = await countVideosForPlatform('tiktok');
  if (count === 0) {
    await seedDemoCreatorAnalytics();
  }
}
