import { and, desc, eq, inArray, notInArray } from 'drizzle-orm';
import { db } from '../db.js';
import {
  tiktokOperatorRecommendations,
  type TikTokOperatorRecommendationType,
} from '../schema.js';
import type { VideoWithMetrics } from '../creator-analytics/types.js';
import type { AccountBaselines } from './types.js';
import {
  hasHighCommentVelocity,
  isMomentumFading,
  isOutperformer,
  isRecentStrong,
  isRecyclingCandidate,
} from './metrics.js';
import { resolveOperatorCreatorId } from './resolve-creator.js';
import type { OperatorRecommendationRow } from './types.js';

const ACTIVE_STATUSES = ['new', 'accepted', 'in_progress', 'prepared', 'scheduled'] as const;

function mapRow(row: typeof tiktokOperatorRecommendations.$inferSelect): OperatorRecommendationRow {
  return {
    id: row.id,
    creatorId: row.creatorId,
    platform: row.platform,
    sourceVideoId: row.sourceVideoId,
    creatorVideoId: row.creatorVideoId,
    recommendationType: row.recommendationType,
    title: row.title,
    explanation: row.explanation,
    supportingMetrics: row.supportingMetrics as Record<string, unknown>,
    confidence: Number(row.confidence),
    priority: row.priority,
    status: row.status,
    relatedContentItemId: row.relatedContentItemId,
    relatedSponsorTag: row.relatedSponsorTag,
    relatedLocationTag: row.relatedLocationTag,
    postPackageId: row.postPackageId,
    metadata: row.metadata as Record<string, unknown>,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
    dismissedAt: row.dismissedAt?.toISOString() ?? null,
    completedAt: row.completedAt?.toISOString() ?? null,
  };
}

function buildRec(
  video: VideoWithMetrics,
  type: TikTokOperatorRecommendationType,
  title: string,
  explanation: string,
  confidence: number,
  priority: number,
  metrics: Record<string, unknown>,
): Omit<typeof tiktokOperatorRecommendations.$inferInsert, 'creatorId'> {
  return {
    platform: 'tiktok',
    sourceVideoId: video.videoId,
    creatorVideoId: video.id,
    recommendationType: type,
    title,
    explanation,
    supportingMetrics: metrics,
    confidence: String(confidence),
    priority,
    status: 'new',
    relatedSponsorTag: video.sponsorTag,
    relatedLocationTag: video.locationTag,
    metadata: {
      contentCategory: video.contentCategory,
      contentPillar: video.contentPillar,
      autoGenerated: true,
    },
  };
}

export async function listRecommendations(
  creatorId?: string,
  options?: { status?: string[]; limit?: number },
): Promise<OperatorRecommendationRow[]> {
  const cid = await resolveOperatorCreatorId(creatorId);
  const statuses = options?.status ?? [...ACTIVE_STATUSES];
  const rows = await db
    .select()
    .from(tiktokOperatorRecommendations)
    .where(
      and(
        eq(tiktokOperatorRecommendations.creatorId, cid),
        inArray(tiktokOperatorRecommendations.status, statuses as never[]),
      ),
    )
    .orderBy(desc(tiktokOperatorRecommendations.priority), desc(tiktokOperatorRecommendations.createdAt))
    .limit(options?.limit ?? 50);
  return rows.map(mapRow);
}

export async function getRecommendation(id: string): Promise<OperatorRecommendationRow | null> {
  const [row] = await db
    .select()
    .from(tiktokOperatorRecommendations)
    .where(eq(tiktokOperatorRecommendations.id, id))
    .limit(1);
  return row ? mapRow(row) : null;
}

export async function updateRecommendationStatus(
  id: string,
  status: OperatorRecommendationRow['status'],
): Promise<OperatorRecommendationRow | null> {
  const now = new Date();
  const patch: Partial<typeof tiktokOperatorRecommendations.$inferInsert> = {
    status,
    updatedAt: now,
  };
  if (status === 'dismissed') patch.dismissedAt = now;
  if (status === 'completed') patch.completedAt = now;

  const [row] = await db
    .update(tiktokOperatorRecommendations)
    .set(patch)
    .where(eq(tiktokOperatorRecommendations.id, id))
    .returning();
  return row ? mapRow(row) : null;
}

export async function linkRecommendationPackage(
  recommendationId: string,
  postPackageId: string,
): Promise<void> {
  await db
    .update(tiktokOperatorRecommendations)
    .set({
      postPackageId,
      status: 'prepared',
      updatedAt: new Date(),
    })
    .where(eq(tiktokOperatorRecommendations.id, recommendationId));
}

export async function refreshAutoRecommendations(
  baselines: AccountBaselines,
  creatorId?: string,
): Promise<number> {
  const cid = await resolveOperatorCreatorId(creatorId);
  const existing = await db
    .select({
      sourceVideoId: tiktokOperatorRecommendations.sourceVideoId,
      recommendationType: tiktokOperatorRecommendations.recommendationType,
    })
    .from(tiktokOperatorRecommendations)
    .where(
      and(
        eq(tiktokOperatorRecommendations.creatorId, cid),
        notInArray(tiktokOperatorRecommendations.status, ['dismissed', 'completed']),
      ),
    );

  const existingKeys = new Set(
    existing.map((e) => `${e.sourceVideoId ?? ''}:${e.recommendationType}`),
  );

  const inserts: Array<typeof tiktokOperatorRecommendations.$inferInsert> = [];

  for (const video of baselines.videos) {
    const metrics = {
      views: video.views,
      engagementRate: video.engagementRate,
      performanceIndex: video.performanceIndex,
      comments: video.comments,
      shares: video.shares,
    };

    if (isOutperformer(video, baselines)) {
      const key = `${video.videoId}:make_sequel`;
      if (!existingKeys.has(key)) {
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'make_sequel',
            'Make a sequel',
            `Your ${video.contentCategory?.replace(/_/g, ' ') ?? 'video'} is running ${video.performanceIndex.toFixed(1)}× above your recent average. Make a sequel while the format is hot.`,
            Math.min(0.95, 0.5 + video.performanceIndex * 0.15),
            video.performanceIndex >= 2 ? 1 : 2,
            metrics,
          ),
        });
        existingKeys.add(key);
      }

      const proofKey = `${video.videoId}:build_sponsor_proof`;
      if (!existingKeys.has(proofKey) && video.views >= 1000) {
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'build_sponsor_proof',
            'Sponsor proof candidate',
            `Strong performance (${video.performanceIndex.toFixed(1)}× average) — add this to sponsor proof and your media kit.`,
            Math.min(0.9, 0.45 + video.performanceIndex * 0.12),
            2,
            metrics,
          ),
        });
        existingKeys.add(proofKey);
      }

      const formatKey = `${video.videoId}:repeat_format`;
      if (!existingKeys.has(formatKey)) {
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'repeat_format',
            'Repeat this format',
            `This ${video.contentPillar ?? video.contentCategory ?? 'format'} is a repeatable winner. Schedule another similar post this week.`,
            Math.min(0.88, 0.4 + video.performanceIndex * 0.1),
            2,
            metrics,
          ),
        });
        existingKeys.add(formatKey);
      }

      if (video.sponsorTag || video.locationTag) {
        const outreachKey = `${video.videoId}:create_outreach_angle`;
        if (!existingKeys.has(outreachKey)) {
          inserts.push({
            creatorId: cid,
            ...buildRec(
              video,
              'create_outreach_angle',
              'Create outreach angle',
              `Turn this outperforming post into a sponsor pitch angle${video.sponsorTag ? ` for ${video.sponsorTag}` : ''}.`,
              0.72,
              3,
              metrics,
            ),
          });
          existingKeys.add(outreachKey);
        }
      }
    }

    if (isRecentStrong(video, baselines)) {
      const followKey = `${video.videoId}:schedule_follow_up`;
      if (!existingKeys.has(followKey)) {
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'schedule_follow_up',
            'Needs follow-up',
            `Strong first 72 hours (${video.performanceIndex.toFixed(1)}× average). Strike while momentum is high.`,
            0.8,
            1,
            metrics,
          ),
        });
        existingKeys.add(followKey);
      }
    }

    if (hasHighCommentVelocity(video, baselines)) {
      const commentKey = `${video.videoId}:investigate_comment_trend`;
      if (!existingKeys.has(commentKey)) {
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'investigate_comment_trend',
            'Reply with video',
            `${video.comments} comments — audience is asking for more. Check comment insights and consider a reply video.`,
            0.75,
            2,
            metrics,
          ),
        });
        existingKeys.add(commentKey);
      }

      const replyKey = `${video.videoId}:reply_with_video`;
      if (!existingKeys.has(replyKey)) {
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'reply_with_video',
            'Reply with video',
            `High comment activity on "${(video.title ?? video.caption ?? 'this video').slice(0, 60)}". Answer top questions on camera.`,
            0.7,
            2,
            metrics,
          ),
        });
        existingKeys.add(replyKey);
      }
    }

    if (video.locationTag && isOutperformer(video, baselines, 1.2)) {
      const locKey = `${video.videoId}:create_product_or_location_followup`;
      if (!existingKeys.has(locKey)) {
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'create_product_or_location_followup',
            'Location follow-up',
            `${video.locationTag} content is resonating. Plan a follow-up visit or part-two while interest is warm.`,
            0.68,
            3,
            metrics,
          ),
        });
        existingKeys.add(locKey);
      }
    }

    if (isMomentumFading(video, baselines)) {
      const fadeKey = `${video.videoId}:prepare_for_tiktok`;
      if (!existingKeys.has(fadeKey)) {
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'prepare_for_tiktok',
            'Momentum is fading',
            `Recent post underperformed (${video.performanceIndex.toFixed(1)}× average). Prepare a stronger hook for your next TikTok in this theme.`,
            0.55,
            3,
            metrics,
          ),
        });
        existingKeys.add(fadeKey);
      }
    }

    if (isRecyclingCandidate(video, baselines)) {
      const recycleKey = `${video.videoId}:repost_or_remix`;
      if (!existingKeys.has(recycleKey)) {
        const label = video.contentCategory?.replace(/_/g, ' ') ?? 'format';
        inserts.push({
          creatorId: cid,
          ...buildRec(
            video,
            'repost_or_remix',
            'Recycle this hit',
            `Your ${label} ran ${video.performanceIndex.toFixed(1)}× your average. Switch the hook, on-screen text, caption, and trending sound — then repost a refreshed cut (same story, new packaging).`,
            Math.min(0.85, 0.45 + video.performanceIndex * 0.1),
            2,
            metrics,
          ),
        });
        existingKeys.add(recycleKey);
      }
    }
  }

  if (inserts.length === 0) return 0;
  await db.insert(tiktokOperatorRecommendations).values(inserts);
  return inserts.length;
}
