import { desc, eq } from 'drizzle-orm';
import { db } from '../db.js';
import { sponsorProofAssets } from '../schema.js';
import { generateOperatorJson } from './ai-helper.js';
import { loadAccountBaselines, toOperatorVideoRef } from './metrics.js';
import { resolveOperatorCreatorId } from './resolve-creator.js';
import type { SponsorProofRow } from './types.js';

function mapProof(row: typeof sponsorProofAssets.$inferSelect): SponsorProofRow {
  return {
    id: row.id,
    creatorId: row.creatorId,
    platform: row.platform,
    sourceVideoId: row.sourceVideoId,
    creatorVideoId: row.creatorVideoId,
    videoTitle: row.videoTitle,
    videoCaption: row.videoCaption,
    thumbnailUrl: row.thumbnailUrl,
    shareUrl: row.shareUrl,
    performanceSnapshot: row.performanceSnapshot as Record<string, unknown>,
    engagementRate: row.engagementRate != null ? Number(row.engagementRate) : null,
    contentCategory: row.contentCategory,
    brandRelevance: row.brandRelevance,
    notes: row.notes,
    proofHeadline: row.proofHeadline,
    proofSummary: row.proofSummary,
    includedInMediaKit: row.includedInMediaKit,
    mediaKitId: row.mediaKitId,
    metadata: row.metadata as Record<string, unknown>,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  };
}

export async function listSponsorProofAssets(creatorId?: string): Promise<SponsorProofRow[]> {
  const cid = await resolveOperatorCreatorId(creatorId);
  const rows = await db
    .select()
    .from(sponsorProofAssets)
    .where(eq(sponsorProofAssets.creatorId, cid))
    .orderBy(desc(sponsorProofAssets.createdAt))
    .limit(30);
  return rows.map(mapProof);
}

export async function buildSponsorProof(
  creatorVideoId: string,
  creatorId?: string,
  notes?: string,
): Promise<SponsorProofRow> {
  const cid = await resolveOperatorCreatorId(creatorId);
  const baselines = await loadAccountBaselines();
  const video = baselines.videos.find((v) => v.id === creatorVideoId);
  if (!video) throw new Error('Video not found');

  const ref = toOperatorVideoRef(video);
  const fallbackHeadline = `${ref.contentCategory?.replace(/_/g, ' ') ?? 'TikTok'} outperformed account average`;
  const fallbackSummary = `This ${ref.contentCategory?.replace(/_/g, ' ') ?? 'review'} outperformed the account average (${ref.performanceIndex.toFixed(1)}× views) and showed strong audience interest${ref.locationTag ? ` in ${ref.locationTag}` : ''}.`;

  const ai = await generateOperatorJson<{ proofHeadline?: string; proofSummary?: string; brandRelevance?: string }>(
    'Write sponsor-facing proof copy for a creator media kit. Return JSON: proofHeadline, proofSummary, brandRelevance. Polished, factual, no invented metrics.',
    {
      video: ref,
      notes,
    },
    {
      proofHeadline: fallbackHeadline,
      proofSummary: fallbackSummary,
      brandRelevance: ref.sponsorTag ?? ref.contentCategory ?? undefined,
    },
  );

  const [row] = await db
    .insert(sponsorProofAssets)
    .values({
      creatorId: cid,
      platform: 'tiktok',
      sourceVideoId: video.videoId,
      creatorVideoId: video.id,
      videoTitle: video.title ?? video.caption?.slice(0, 120) ?? 'TikTok video',
      videoCaption: video.caption,
      thumbnailUrl: video.thumbnailUrl,
      shareUrl: video.postUrl,
      performanceSnapshot: {
        views: video.views,
        likes: video.likes,
        comments: video.comments,
        shares: video.shares,
        engagementRate: video.engagementRate,
        performanceIndex: video.performanceIndex,
      },
      engagementRate: String(video.engagementRate),
      contentCategory: video.contentCategory,
      brandRelevance: ai.brandRelevance ?? ref.sponsorTag ?? ref.contentCategory ?? undefined,
      notes: notes ?? null,
      proofHeadline: ai.proofHeadline ?? fallbackHeadline,
      proofSummary: ai.proofSummary ?? fallbackSummary,
      metadata: { autoGenerated: true },
    })
    .returning();

  return mapProof(row!);
}

export async function updateSponsorProof(
  id: string,
  patch: Partial<{
    proofHeadline: string;
    proofSummary: string;
    notes: string | null;
    includedInMediaKit: boolean;
    mediaKitId: string | null;
  }>,
): Promise<SponsorProofRow | null> {
  const [row] = await db
    .update(sponsorProofAssets)
    .set({ ...patch, updatedAt: new Date() })
    .where(eq(sponsorProofAssets.id, id))
    .returning();
  return row ? mapProof(row) : null;
}

export async function linkProofToMediaKit(
  proofId: string,
  mediaKitId: string,
): Promise<SponsorProofRow | null> {
  return updateSponsorProof(proofId, { includedInMediaKit: true, mediaKitId });
}
